"use strict";

/**
 * Full E2E hardware test suite for the ipod-shuffle system.
 * Exercises every feature against a REAL iPod Shuffle device at /Volumes/IPOD.
 *
 * Run:
 *   # Start engine + node first, then:
 *   node e2e/run.js
 *
 * Requires:
 *   - Go engine running on :8765
 *   - Moleculer node running on :3280
 *   - iPod Shuffle mounted at /Volumes/IPOD
 *   - Test audio at /tmp/e2e-audio/ (generated by the setup script)
 */

const {
	api,
	countDeviceAudioFiles,
	getITunesSDSize,
	getIdentity,
	waitForSync,
	wipeDevice,
	assert,
	sleep,
	AUDIO_DIR,
} = require("./helpers");

const fs = require("node:fs");
const path = require("node:path");

let totalTests = 0;
let passedTests = 0;
let failedTests = 0;
const failures = [];

async function test(name, fn) {
	totalTests++;
	process.stdout.write(`  ${name} ... `);
	try {
		await fn();
		passedTests++;
		console.log("✓");
	} catch (err) {
		failedTests++;
		failures.push({ name, error: err.message });
		console.log(`✗ ${err.message}`);
	}
}

function section(name) {
	console.log(`\n━━━ ${name} ━━━`);
}

// ─── GLOBAL STATE ───
let deviceId = null;
let playlistId = null;
let playlist2Id = null;
let groupId = null;
let cloneId = null;
let aliasId = null;
let trackIds = [];

async function main() {
	console.log("╔══════════════════════════════════════════════════════════╗");
	console.log("║  IPOD SHUFFLE — FULL E2E HARDWARE TEST SUITE             ║");
	console.log("╚══════════════════════════════════════════════════════════╝");
	console.log(`  Device: ${process.env.E2E_DEVICE_MOUNT || "/Volumes/IPOD"}`);
	console.log(`  Audio:  ${AUDIO_DIR}`);
	console.log(`  Time:   ${new Date().toISOString()}`);

	// ═══ SETUP: wipe device to known clean state ═══
	section("SETUP — Wipe device to clean state");
	await test("discover device", async () => {
		const res = await api("GET", "/api/devices");
		assert(res.status === 200, `expected 200, got ${res.status}`);
		const devices = res.body.devices || [];
		assert(devices.length > 0, "no devices discovered");
		// Pick the first device with an iPod_Control dir
		deviceId = devices[0].id;
		console.log(`\n    → device: ${devices[0].name} (${deviceId})`);
	});

	if (!deviceId) {
		console.log("\n❌ No device found. Aborting.");
		process.exit(1);
	}

	// Get the device's current state and clear ALL existing assignments
	// so our sync tests only see our test data.
	const stateRes0 = await api("GET", `/api/devices/${deviceId}/state`);
	if (stateRes0.status === 200 && stateRes0.body.assignments) {
		const existingPlaylists = stateRes0.body.assignments.assignedPlaylistIds || [];
		for (const pid of existingPlaylists) {
			await api("POST", `/api/devices/${deviceId}/playlists/${pid}`); // toggle off
		}
		// Also clear group assignments
		const existingGroups = stateRes0.body.assignments.assignedGroupIds || [];
		for (const gid of existingGroups) {
			await api("POST", `/api/devices/${deviceId}/groups/${gid}`); // toggle off
		}
	}

	await test("wipe device", async () => {
		const result = await wipeDevice(deviceId);
		assert(result.wiped === true, "wipe did not return success");
		await sleep(2000); // let filesystem settle
	});

	await test("device is empty after wipe", async () => {
		const count = countDeviceAudioFiles();
		assert(count === 0, `expected 0 files, found ${count}`);
		const sdSize = getITunesSDSize();
		assert(sdSize === 132, `expected iTunesSD=132 bytes (empty), got ${sdSize}`);
	});

	// ═══ DISCOVERY ═══
	section("DISCOVERY — Device detection & capacity");
	await test("device has disk capacity", async () => {
		const res = await api("GET", "/api/devices");
		const dev = res.body.devices.find((d) => d.id === deviceId);
		assert(dev, "device not found in refresh response");
		assert(dev.totalBytes > 0, `totalBytes is 0`);
		assert(dev.freeBytes > 0, `freeBytes is 0`);
		assert(dev.totalBytes > dev.freeBytes, `total < free`);
	});

	await test("device is online", async () => {
		const res = await api("GET", `/api/devices/${deviceId}/online`);
		assert(res.body === true, `expected online=true, got ${res.body}`);
	});

	await test("identity file preserved after wipe", async () => {
		const ident = getIdentity();
		assert(ident !== null, "no identity file");
		assert(ident.id === deviceId || ident.id.startsWith("mount-"), `unexpected id: ${ident?.id}`);
		assert(ident.name && ident.name.length > 0, "no name in identity");
	});

	// ═══ LIBRARY ═══
	section("LIBRARY — Add test audio fixtures & scan");
	await test("add library root", async () => {
		const res = await api("POST", "/api/library/roots", { rootPath: AUDIO_DIR });
		assert(res.status === 200, `expected 200, got ${res.status}: ${res.raw}`);
		assert(res.body.scanned >= 3, `expected ≥3 scanned, got ${res.body.scanned}`);
	});

	await test("tracks registered after scan", async () => {
		const res = await api("GET", "/api/tracks");
		assert(res.status === 200, `expected 200, got ${res.status}`);
		const tracks = Array.isArray(res.body) ? res.body : [];
		const e2eTracks = tracks.filter((t) => t.sourcePath.startsWith(AUDIO_DIR));
		assert(e2eTracks.length >= 3, `expected ≥3 e2e tracks, got ${e2eTracks.length}`);
		// Verify extensions are classified
		const mp3s = e2eTracks.filter((t) => t.extension === ".mp3");
		assert(mp3s.length >= 2, `expected ≥2 mp3s, got ${mp3s.length}`);
		trackIds = e2eTracks.map((t) => t.id);
	});

	await test("tracks have correct sizes", async () => {
		const res = await api("GET", "/api/tracks");
		const e2eTracks = res.body.filter((t) => t.sourcePath.startsWith(AUDIO_DIR) && t.exists);
		for (const t of e2eTracks) {
			assert(t.sizeBytes > 0, `track ${t.fileName} has size 0`);
			assert(t.exists === true, `track ${t.fileName} marked as missing`);
		}
		// Update trackIds to only existing e2e tracks (filters out stale ones from previous runs)
		trackIds = e2eTracks.map((t) => t.id);
	});

	// ═══ PLAYLISTS ═══
	section("PLAYLISTS — CRUD, clone, alias");
	await test("create playlist", async () => {
		const res = await api("POST", "/api/playlists", { name: "E2E Test Mix" });
		assert(res.status === 200, `expected 200, got ${res.status}`);
		assert(res.body.name === "E2E Test Mix", `wrong name: ${res.body.name}`);
		playlistId = res.body.id;
	});

	await test("add tracks to playlist", async () => {
		const res = await api("POST", `/api/playlists/${playlistId}/tracks`, { trackIds });
		assert(res.status === 200, `expected 200, got ${res.status}`);
		assert(res.body.trackIds.length === trackIds.length, `track count mismatch`);
	});

	await test("create second playlist", async () => {
		const res = await api("POST", "/api/playlists", { name: "E2E Clone Source" });
		playlist2Id = res.body.id;
		const addRes = await api("POST", `/api/playlists/${playlist2Id}/tracks`, { trackIds: trackIds.slice(0, 2) });
		assert(addRes.body.trackIds.length === 2, `expected 2 tracks, got ${addRes.body.trackIds.length}`);
	});

	await test("clone playlist", async () => {
		const res = await api("POST", `/api/playlists/${playlistId}/clone`);
		assert(res.status === 200, `expected 200, got ${res.status}`);
		assert(res.body.trackIds.length === trackIds.length, `clone has wrong track count`);
		assert(res.body.aliasOf === null, `clone should not be an alias`);
		cloneId = res.body.id;
	});

	await test("create alias", async () => {
		const res = await api("POST", `/api/playlists/${playlistId}/alias`);
		assert(res.status === 200, `expected 200, got ${res.status}`);
		assert(res.body.aliasOf === playlistId, `alias should point to source`);
		assert(res.body.trackIds.length === 0, `alias should have no own tracks`);
		aliasId = res.body.id;
	});

	await test("resolve alias to source", async () => {
		// The resolve endpoint should show source tracks through the alias.
		const res = await api("GET", `/api/sync/${deviceId}/resolve`); // won't have alias assigned yet
		// Just verify the alias exists in playlist list
		const listRes = await api("GET", "/api/playlists");
		const alias = listRes.body.find((p) => p.id === aliasId);
		assert(alias, "alias not found in playlist list");
		assert(alias.aliasOf === playlistId, "alias doesn't reference source");
	});

	await test("reorder tracks in playlist", async () => {
		const reversed = [...trackIds].reverse();
		const res = await api("POST", `/api/playlists/${playlistId}/order`, { trackIds: reversed });
		assert(res.status === 200, `expected 200, got ${res.status}`);
		assert(res.body.trackIds[0] === reversed[0], `reorder didn't take effect`);
	});

	// ═══ GROUPS ═══
	section("GROUPS — Create, assign, tree");
	await test("create group", async () => {
		const res = await api("POST", "/api/groups", { name: "E2E Group" });
		assert(res.status === 200, `expected 200, got ${res.status}`);
		groupId = res.body.id;
	});

	await test("move playlist to group", async () => {
		const res = await api("PATCH", `/api/playlists/${playlistId}/group`, { groupId });
		assert(res.status === 200, `expected 200, got ${res.status}`);
		assert(res.body.groupId === groupId, `groupId not set`);
	});

	await test("list groups ordered", async () => {
		const res = await api("GET", "/api/groups");
		assert(res.status === 200, `expected 200, got ${res.status}`);
		const found = res.body.find((g) => g.id === groupId);
		assert(found, "group not found in list");
		assert(found.name === "E2E Group", `wrong name: ${found.name}`);
	});

	// ═══ DEVICE ASSIGNMENT ═══
	section("DEVICE ASSIGNMENT — Playlists + state");
	await test("assign playlist to device", async () => {
		const res = await api("POST", `/api/devices/${deviceId}/playlists/${playlistId}`);
		assert(res.status === 200, `expected 200, got ${res.status}`);
	});

	await test("device state reflects assignment", async () => {
		const res = await api("GET", `/api/devices/${deviceId}/state`);
		assert(res.status === 200, `expected 200, got ${res.status}`);
		const state = res.body;
		assert(state.assignments.assignedPlaylistIds.includes(playlistId), "playlist not in assigned list");
		assert(state.resolve.trackCount === trackIds.length, `resolve track count wrong: ${state.resolve.trackCount} vs ${trackIds.length}`);
	});

	// ═══ SYNC ═══
	section("SYNC — Full sync with progress polling");

	// Before sync, get the CURRENT playlist track order (after the reversal test).
	// This is the order that should appear on the device.
	let expectedOrder = [];
	{
		const plRes = await api("GET", `/api/playlists/${playlistId}`);
		expectedOrder = plRes.body.trackIds;
	}

	await test("start sync", async () => {
		const res = await api("POST", `/api/sync/${deviceId}`);
		assert(res.status === 200, `expected 200, got ${res.status}`);
		assert(res.body.status === "running", `expected running, got ${res.body.status}`);
	});

	await test("sync completes", async () => {
		const job = await waitForSync(deviceId, 120000);
		assert(job.status === "completed", `expected completed, got ${job.status}`);
		assert(job.result.manifest.length === trackIds.length, `manifest has ${job.result.manifest.length}, expected ${trackIds.length}`);
	});

	await test("files appear on device", async () => {
		await sleep(1000); // let FS settle
		const count = countDeviceAudioFiles();
		assert(count === trackIds.length, `expected ${trackIds.length} files on device, found ${count}`);
	});

	await test("iTunesSD is non-trivial size", async () => {
		const sdSize = getITunesSDSize();
		assert(sdSize > 132, `iTunesSD is still empty (132 bytes), got ${sdSize}`);
	});

	await test("identity snapshot has tracks", async () => {
		const ident = getIdentity();
		assert(ident.snapshot, "no snapshot in identity");
		assert(ident.snapshot.totalTracks === trackIds.length, `snapshot tracks: ${ident.snapshot?.totalTracks} vs ${trackIds.length}`);
		assert(ident.snapshot.playlists.length >= 1, "no playlists in snapshot");
	});

	// ═══ TRACK ORDER VERIFICATION ═══
	section("TRACK ORDER — Device paths match playlist order");
	await test("snapshot devicePaths are sequential S00000, S00001, ...", async () => {
		const ident = getIdentity();
		const tracks = ident.snapshot.playlists.flatMap((p) => p.tracks);
		// Extract the S##### index from each devicePath
		const indices = tracks.map((t) => {
			const match = t.devicePath.match(/S(\d+)\./);
			return match ? parseInt(match[1], 10) : -1;
		});
		// Verify they're 0, 1, 2, 3, ... in order
		for (let i = 0; i < indices.length; i++) {
			assert(indices[i] === i, `track ${i} has devicePath index ${indices[i]}, expected ${i}`);
		}
	});

	await test("snapshot track order matches playlist order", async () => {
		const ident = getIdentity();
		const snapshotTracks = ident.snapshot.playlists.flatMap((p) => p.tracks);
		// The snapshot stores track IDs in the order they were synced.
		// This should match the expectedOrder (the playlist's trackIds at sync time).
		const snapshotTrackIds = snapshotTracks.map((t) => t.id);
		assert(snapshotTrackIds.length === expectedOrder.length,
			`snapshot has ${snapshotTrackIds.length} tracks, expected ${expectedOrder.length}`);
		for (let i = 0; i < expectedOrder.length; i++) {
			assert(snapshotTrackIds[i] === expectedOrder[i],
				`position ${i}: snapshot has ${snapshotTrackIds[i]}, expected ${expectedOrder[i]}`);
		}
	});

	await test("files on disk have correct sizes matching their source", async () => {
		const ident = getIdentity();
		const tracksRes = await api("GET", "/api/tracks");
		const trackById = new Map(tracksRes.body.map((t) => [t.id, t]));

		const snapshotTracks = ident.snapshot.playlists.flatMap((p) => p.tracks);
		for (const snapTrack of snapshotTracks) {
			const sourceTrack = trackById.get(snapTrack.id);
			assert(sourceTrack, `source track ${snapTrack.id} not found`);
			// Verify the file on disk at the device path has the correct size
			const deviceFile = path.join(process.env.E2E_DEVICE_MOUNT || "/Volumes/IPOD",
				"iPod_Control", "Music", "F00",
				path.basename(snapTrack.devicePath));
			const stat = fs.statSync(deviceFile);
			assert(stat.size === sourceTrack.sizeBytes,
				`file ${deviceFile} is ${stat.size} bytes, source is ${sourceTrack.sizeBytes}`);
		}
	});

	// ═══ SYNC DIFF ═══
	section("SYNC DIFF — In-sync, then out-of-sync");
	await test("device shows in-sync after sync", async () => {
		const res = await api("GET", `/api/devices/${deviceId}/state`);
		const diff = res.body.diff;
		assert(diff.status === "in-sync", `expected in-sync, got ${diff.status}`);
	});

	await test("device shows out-of-sync after adding a track", async () => {
		// Add a new track to the playlist (not yet on device)
		const addRes = await api("POST", `/api/playlists/${playlistId}/tracks`, { trackIds: [trackIds[0]] });
		// It's already there, so let's add a new file instead
		// Create a new silent file
		const newFile = path.join(AUDIO_DIR, "e2e-extra.mp3");
		fs.copyFileSync(path.join(AUDIO_DIR, "silence-5s.mp3"), newFile);
		await sleep(500);

		// Add the new file to the library
		const trackRes = await api("POST", "/api/library/tracks", { sourcePath: newFile });
		assert(trackRes.status === 200, `addTrack failed: ${trackRes.status}`);
		const newTrackId = trackRes.body.track.id;

		// Add to playlist
		await api("POST", `/api/playlists/${playlistId}/tracks`, { trackIds: [newTrackId] });

		// Now check state — should be out of sync
		const stateRes = await api("GET", `/api/devices/${deviceId}/state`);
		const diff = stateRes.body.diff;
		assert(diff.status === "out-of-sync", `expected out-of-sync, got ${diff.status}`);
		assert(diff.added.length >= 1, `expected ≥1 added, got ${diff.added.length}`);

		// Clean up the extra file
		try { fs.unlinkSync(newFile); } catch {}
	});

	// ═══ REORDER + RE-SYNC ═══
	section("REORDER + RE-SYNC — New order reflected on device");
	await test("reorder playlist and re-sync", async () => {
		// Set a new order: move the last track to first
		const plRes = await api("GET", `/api/playlists/${playlistId}`);
		const currentOrder = plRes.body.trackIds;
		const newOrder = [currentOrder[currentOrder.length - 1], ...currentOrder.slice(0, -1)];
		const reorderRes = await api("POST", `/api/playlists/${playlistId}/order`, { trackIds: newOrder });
		assert(reorderRes.status === 200, `reorder failed: ${reorderRes.status}`);

		// Re-sync
		const syncRes = await api("POST", `/api/sync/${deviceId}`);
		assert(syncRes.status === 200, `sync start failed`);
		const job = await waitForSync(deviceId, 120000);
		assert(job.status === "completed", `re-sync failed: ${job.status}`);

		// Verify the new order is in the snapshot
		const ident = getIdentity();
		const snapshotTracks = ident.snapshot.playlists.flatMap((p) => p.tracks);
		const snapshotIds = snapshotTracks.map((t) => t.id);
		assert(snapshotIds[0] === newOrder[0],
			`after re-sync, first track should be ${newOrder[0]}, got ${snapshotIds[0]}`);
		assert(snapshotIds.length === newOrder.length,
			`snapshot has ${snapshotIds.length}, expected ${newOrder.length}`);

		// Verify devicePaths are still sequential
		for (let i = 0; i < snapshotTracks.length; i++) {
			const match = snapshotTracks[i].devicePath.match(/S(\d+)\./);
			const idx = match ? parseInt(match[1], 10) : -1;
			assert(idx === i, `after re-sync, track ${i} has devicePath index ${idx}, expected ${i}`);
		}
	});

	// ═══ WIPE ═══
	section("WIPE — Clean device, preserve identity");
	await test("wipe removes all audio", async () => {
		const result = await wipeDevice(deviceId);
		assert(result.wiped === true, "wipe failed");
		await sleep(2000);
		const count = countDeviceAudioFiles();
		assert(count === 0, `expected 0 files, found ${count}`);
	});

	await test("iTunesSD is empty after wipe", async () => {
		const sdSize = getITunesSDSize();
		assert(sdSize === 132, `expected 132 bytes, got ${sdSize}`);
	});

	await test("identity survives wipe (id + name)", async () => {
		const ident = getIdentity();
		assert(ident !== null, "identity file missing after wipe");
		assert(ident.id, "identity id missing");
		assert(ident.name, "identity name missing");
		assert(!ident.snapshot || ident.snapshot === null || ident.snapshot === undefined,
			"snapshot should be cleared after wipe");
	});

	// ═══ REVALIDATE ═══
	section("REVALIDATE — Missing file detection");
	await test("revalidate detects deleted file", async () => {
		// Add a file, scan it, then delete it, then revalidate.
		const testFile = path.join(AUDIO_DIR, "e2e-delete-me.mp3");
		fs.copyFileSync(path.join(AUDIO_DIR, "silence-1s.mp3"), testFile);
		await sleep(500);

		const trackRes = await api("POST", "/api/library/tracks", { sourcePath: testFile });
		assert(trackRes.status === 200, "addTrack failed");
		const trackId = trackRes.body.track.id;
		assert(trackRes.body.track.exists === true, "track should exist");

		// Delete the file
		fs.unlinkSync(testFile);
		await sleep(500);

		// Revalidate
		const revRes = await api("POST", "/api/library/revalidate");
		assert(revRes.status === 200, "revalidate failed");

		// Check the track is now marked missing
		const tracksRes = await api("GET", "/api/tracks");
		const track = tracksRes.body.find((t) => t.id === trackId);
		assert(track, "track not found after revalidate");
		assert(track.exists === false, `expected exists=false, got ${track.exists}`);
	});

	// ═══ CLEANUP ═══
	section("CLEANUP — Remove test data");
	await test("remove test playlists", async () => {
		if (playlistId) await api("DELETE", `/api/playlists/${playlistId}`);
		if (playlist2Id) await api("DELETE", `/api/playlists/${playlist2Id}`);
		if (cloneId) await api("DELETE", `/api/playlists/${cloneId}`);
		if (aliasId) await api("DELETE", `/api/playlists/${aliasId}`);
		// Verify they're gone
		const res = await api("GET", "/api/playlists");
		const remaining = res.body.filter((p) => [playlistId, playlist2Id, cloneId, aliasId].includes(p.id));
		assert(remaining.length === 0, `${remaining.length} test playlists still exist`);
	});

	await test("remove test group", async () => {
		if (groupId) await api("DELETE", `/api/groups/${groupId}`);
		const res = await api("GET", "/api/groups");
		const found = res.body.find((g) => g.id === groupId);
		assert(!found, "group still exists");
	});

	// ═══ RESULTS ═══
	console.log("\n╔══════════════════════════════════════════════════════════╗");
	console.log(`║  RESULTS: ${passedTests}/${totalTests} passed, ${failedTests} failed${" ".repeat(23 - String(passedTests + failedTests).length)}║`);
	console.log("╚══════════════════════════════════════════════════════════╝");

	if (failures.length > 0) {
		console.log("\n❌ FAILURES:");
		for (const f of failures) {
			console.log(`  • ${f.name}: ${f.error}`);
		}
	}

	process.exit(failedTests > 0 ? 1 : 0);
}

main().catch((err) => {
	console.error("\n💥 FATAL ERROR:", err);
	process.exit(2);
});
